services:
    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - '5434:5432'
        environment:
            - POSTGRES_DB=django_core_tutorial
            - POSTGRES_USER=postgres2
            - POSTGRES_PASSWORD=qwerty123321
        volumes:
            - postgresql-data:/var/lib/postgresql/data

volumes:
    postgresql-data:
        driver: local
