name: Quality Assurance
on: [pull_request, workflow_call]


jobs:
    quality-assurance:
        name: Quality Assurance
        runs-on: ubuntu-latest
        container: python:3.10.4-buster

        services:
            db:
                image: postgres:latest
                env:
                    POSTGRES_DB: django_core_tutorial
                    POSTGRES_USER: postgres2
                    POSTGRES_PASSWORD: qwerty123321

        steps:
            - uses: actions/checkout@v2

            - name: Install Poetry
              uses: abatilo/actions-poetry@v2.0.0
              with:
                poetry-version: 1.4.2

            - name: Install Dependencies
              run: make install && make install-pre-commit

            - name: Test
              run: make test
              env:
                CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
                CORE_SETTING_LOCAL_SETTINGS_PATH: './cooking_core/project/settings/templates/settings.github.py'
